version: '3.8'

services:
  github-pr-analytics:
    build: .
    env_file:
      - .env.production
    ports:
      - "3000:3000"    # Map host 3000 to container 3000
    restart: always    # Ensure the container restarts if it crashes
