version: '3.8'

services:
  github-pr-analytics:
    build: .
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/github_analytics

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""   # If you use authentication, set these accordingly
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_BASICAUTH_USERNAME: admin   # Web UI login username
      ME_CONFIG_BASICAUTH_PASSWORD: admin   # Web UI login password
    depends_on:
      - mongo

volumes:
  mongo-data:
