version: '3.8'

services:
  github-pr-analytics:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - .env.development
